[project]
name = "eda-copilot-backend"
version = "0.1.0"
description = "FastAPI backend for EDA Copilot"
requires-python = ">=3.10"
dependencies = [
  "fastapi>=0.110.0",
  "uvicorn[standard]>=0.27.0",
  "pandas>=2.2.0",
  "numpy>=1.26.0",
  "scipy>=1.11.0"
]

[tool.setuptools]
packages = ["app"]
